version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
    # create pull requests against part-1 (used for @storyblok/create-demo)
    target-branch: "part-1"
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope